// Module included in the following assemblies:
//
// * installing/installing_gcp/installing-gcp-account.adoc

[id="minimum-required-permissions-ipi-gcp-xpn"]
= Required GCP permissions for shared VPC installations

When you are installing a cluster to a link:https://cloud.google.com/vpc/docs/shared-vpc[shared VPC], you must configure the service account for both the host project and the service project. If you are not installing to a shared Virtual Private Cloud (VPC), you can skip this section.

You must apply the minimum roles required for a standard installation as listed above, to the service project.

[NOTE]
====
You can use fine-grained permissions for a Cloud Credential Operator configured that operates in either passthrough or manual credentials mode. However, you cannot use granular permissions in passthrough credentials mode.
====

In addition, the host project must apply one of the following configurations to the service account:

.Required permissions for creating firewalls in the host project
[%collapsible]
====
* `projects/<host-project>/roles/dns.networks.bindPrivateDNSZone`
* `roles/compute.networkAdmin`
* `roles/compute.securityAdmin`
====

.Required minimal permissions
[%collapsible]
====
* `projects/<host-project>/roles/dns.networks.bindPrivateDNSZone`
* `roles/compute.networkUser`
====
