:_mod-docs-content-type: REFERENCE
[id="rn-ocp-release-notes-new-features_{context}"]
= New features and enhancements

This release adds improvements related to the following components and concepts:

[id="ocp-release-notes-api_{context}"]
== API server

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-auth_{context}"]
== Authentication and authorization


[id="ocp-release-notes-auto_{context}"]
== Autoscaling


[id="ocp-release-notes-edge-computing_{context}"]
== Edge computing

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////


[id="ocp-release-notes-etcd_{context}"]
== etcd

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////


[id="ocp-release-notes-extensions_{context}"]
== Extensions ({olmv1})

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

// [id="ocp-release-notes-hcp_{context}"]
// == Hosted control planes

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-ibm-power_{context}"]
== IBM Power

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-ibm-z-linux-one_{context}"]
== IBM Z and IBM LinuxONE

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

// [id="ocp-release-notes-ibm-power-linuxone_{context}"]
// == IBM Power, IBM Z, and IBM LinuxOne support matrix

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

// [id="ocp-release-notes-insights-operator_{context}"]
// == Insights Operator

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-install-update_{context}"]
== Installation and update


[id="ocp-release-notes-machine-config-operator_{context}"]
== Machine Config Operator


[id="ocp-release-notes-machine-management_{context}"]
== Machine management


[id="ocp-release-notes-monitoring_{context}"]
== Monitoring

// This should be left for a little while to get users used to the fact that they will find release notes aViewing metrics collected by the Kubernetes NMState Operatort a new place.


[id="ocp-release-notes-networking_{context}"]
== Networking

Kubernetes NMState Operator extends metrics support:
+
The Kubernetes NMState Operator can now collect metrics from the following Kubernetes components:
+
* `kubernetes_nmstate_policies_status`, which tracks the active status of `NodeNetworkConfigurationPolicy` (NNCP) resources across the cluster.
+
* `kubernetes_nmstate_enactments_status`, which tracks the active status of `NodeNetworkConfigurationEnactment` (NNCE) resources on a per-node basis.
+
For more information, see xref:../networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc#viewing-stats-collected-kubernetes-nmtate-op_k8s-nmstate-about-the-k8s-nmstate-operator[Viewing metrics collected by the Kubernetes NMState Operator].

[id="ocp-release-notes-nodes_{context}"]
== Nodes

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-operator-development_{context}"]
== Operator development

////
This section applies to the removed Operator SDK and the Operator base images that are still supported.
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-post-install-configuration_{context}"]
== Postinstallation configuration

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////


// [id="ocp-release-notes-rhcos_{context}"]
// == Red Hat Enterprise Linux CoreOS (RHCOS)

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-scale-and-perform_{context}"]
== Scalability and performance


// [id="ocp-release-notes-support-sigstore_{context}"]
// == Support for sigstore bring your own PKI (BYOPKI) image validation

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

[id="ocp-release-notes-web-console_{context}"]
== Web console

////
Instructions: Add entries in the following format:

Item description::
+
Detailed information.
////

