# This CI configuration compiles the internal and external versions
# of the release notes and publishes them using GitLab Pages,
# along with the generated status table.

## Build the release notes using aCoRNs
acorns:
  image: quay.io/msuchane/acorns:latest
  stage: build
  tags:
    - shared
  artifacts:
    paths:
      - 'acorns/generated'
  script:
    - acorns --version
    - acorns build

## Compile HTML previews from the generated AsciiDoc
pages:
  image: asciidoctor/docker-asciidoctor:latest
  stage: deploy
  tags:
    - shared
  variables:
    OUT_DIR: public/$CI_COMMIT_REF_NAME
  script:
    - mkdir -p $OUT_DIR
    - asciidoctor --safe -vn preview-index.adoc
    - asciidoctor --safe -vn main.adoc
    - asciidoctor --safe -vn internal.adoc
    - cp preview-index.html $OUT_DIR/index.html
    - cp main.html $OUT_DIR/external.html
    - cp internal.html $OUT_DIR/internal.html
    - cp acorns/generated/status-table.html $OUT_DIR/status-table.html
    - cp acorns/generated/status-table.json $OUT_DIR/status-table.json
    - printf "<p>Latest generated release:</p><p><a href=$CI_COMMIT_REF_NAME>$CI_COMMIT_REF_NAME</a></p>" > public/index.html
  artifacts:
    paths:
      - public
